name: CD Workflow
on: [push]

jobs:
   deploy:
     runs-on: ubuntu-latest
     env:
       ssh_key: ${{ secrets.SSH_KEY }}
     steps:
       - uses: actions/checkout@v3
       - run: |
          mkdir -p ~/.ssh && \
          echo "$ssh_key" | base64 -d > ~/.ssh/id_rsa && \
          chmod 0600 ~/.ssh/id_rsa
       - run: ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org mkdir -p zinura
       - run: ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org touch zinura/task41.txt
       - run: python3 task.py ${{ secrets.SEED }} > task42.txt
       - run: scp -o StrictHostKeyChecking=no task42.txt bdb2c2023q4_guest_3@brain-client.bigdatateam.org:zinura/

